# Generated by Django 5.0.3 on 2024-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Regional Accounts manager', 'Regional Accounts manager'), ('Regional Sales Manager', 'Regional Sales Manager'), ('Chief Technical Officer', 'Chief Technical Officer'), ('Regional SCM manager', 'Regional SCM manager')], default='Regional Sales Manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(choices=[('Accounts', 'Accounts'), ('HR', 'HR'), ('Sales', 'Sales'), ('Inventory', 'Inventory'), ('Tech', 'Tech')], max_length=100),
        ),
    ]
