# Generated by Django 5.0.3 on 2024-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_userprofile_role_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Regional Accounts manager', 'Regional Accounts manager'), ('Regional Sales Manager', 'Regional Sales Manager'), ('Chief Technical Officer', 'Chief Technical Officer'), ('Regional SCM manager', 'Regional SCM manager'), ('Sales Executive', 'Sales Executive'), ('Accounts Executive', 'Accounts Executive'), ('HR Executive', 'HR Executive'), ('IT Engineer', 'IT Engineer'), ('SCM Executive', 'SCM Executive')], default='Regional Sales Manager', max_length=100),
        ),
    ]
