# Generated by Django 5.0.3 on 2024-11-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_client_added_by_client_date_added_invoice_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=150),
        ),
    ]
