# Generated by Django 5.0.3 on 2024-11-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
