# Generated by Django 5.0.3 on 2024-11-01 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_opportunity_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_receipt',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.opportunity'),
        ),
    ]
