# Generated by Django 5.0.3 on 2024-11-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_invoice_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping_receipt',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
