# Generated by Django 5.0.3 on 2024-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_shipping_receipt_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_qty',
            field=models.IntegerField(default=0),
        ),
    ]
